- hosts: sonarservers
   become: true
   tasks:
    - name: add sonaruser
      user:
        name: sonar
    - name: get_installer
      get_url:
        url: https://binaries.sonarsource.com/Distribution/sonarqube/sonarqube-9.6.1.59531.zip
        dest: /tmp/
    - name: copy
      copy:
        src: /tmp/sonarqube-9.6.1.59531.zip
        dest: /opt/
        remote_src: yes
    - name: install
      unarchive:
        src: /opt/sonarqube-9.6.1.59531.zip
        dest: /opt/
        remote_src: yes
    - name: Change file ownership, group and permissions
      file:
        path: /opt/sonarqube-9.6.1.59531
        owner: sonar
        group: sonar
        recurse: yes
        state: directory
    - name: chmod 755 /opt/sonarqube
      file:
        path: /opt/sonarqube-9.6.1.59531
        recurse: yes
        mode:  0775

    - name: start service
      become_user: sonar
      shell: sh /opt/sonarqube-9.6.1.59531/bin/linux-x86-64/sonar.sh start
